### ISSUE TITLE
Hi, Would you please publish trained models?

### ISSUE THREAD

**Issue by CoinCheung** [cuihaoleo/kaggle-dfdc#2]
Hi, 

Thanks for publishing this repo!!! it seems that it is quite time-consuming to download the videos and train the model. Would you please share the model you trained ?

**Comment by cuihaoleo** [comment]
Hi, please check README. All pretrained weight files have already been released on [GDrive](https://drive.google.com/drive/folders/1ttye8HFwYJA-P8WANGSOLPtC787xGZta).

You can also find our notebook (with data) on Kaggle:
https://www.kaggle.com/cuihaoleo/dfdc-private-lb-4th-place-submission
