### ISSUE TITLE
dfdc.json and dfdc-data.csv

### ISSUE THREAD

**Issue by Aminkhormali** [cuihaoleo/kaggle-dfdc#3]
Can you please let me know how did you generate dfdc.json and dfdc-data.csv files? I couldn't find any script that generates these two files. I appreciate it if you can help me with this issue.

**Comment by wangxinxin98** [comment]
> Can you please let me know how did you generate dfdc.json and dfdc-data.csv files? I couldn't find any script that generates these two files. I appreciate it if you can help me with this issue.

Hello! I have encountered the same problem. Have you found a solution?

**Comment by cuihaoleo** [comment]
They are output by some one-time-use scripts. Sorry we didn't keep it, but it should be quite easy to implement one.

I generated `dfdc-data.csv` . I can give you some details:
- `name` and `is_fake` columns is from `metadata.json` in offical DFDC datasets
- You can get `n_frame` column with some video parsing library (I used `cv2` aka opencv)
- Last column `set_name` indicates train/valid/test set split:
  - If a video is from the same origin with one of 400 Kaggle public test videos, then it is marked as test data;
  - For other videos, they are randomly assigned to train/valid set.

@yoctta generated `dfdc.json`. I don't know the detail. Seemingly it is a json file with such structure:
```
{
    "train": [["sltfpveqzb", 1], ["rqzecufyma", 1] ....... ],
    "test": [["lebzjtusnr", 1], ["blszgmxkvu", 0] ....... ],
    "valid": [["urfuhntprf", 0], ["naqivbtyog", 1] ....... ],
}
```
The meaning looks obvious. Nested two-element tuple is video name and its label. You can get it by parsing `metadata.json`.
