### ISSUE TITLE
There is somthing wrong with the test reault on the DFDC test_videos.

### ISSUE THREAD

**Issue by zhangconghhh** [cuihaoleo/kaggle-dfdc#6]
I run the submission.py with the provide model on the released DFDC dataset on the webpage (https://www.kaggle.com/c/deepfake-detection-challenge/data). But the acc score is 0.5, here is the score after I run the test code. If there is something wrong with my test code.
	
[submisson.docx](https://github.com/cuihaoleo/kaggle-dfdc/files/4812166/submisson.docx)

**Comment by cuihaoleo** [comment]
What does "acc score" mean and how do you calculate it?

I don't see problems with your submission result. The logloss is 0.0404. Fairly good, isn't it?
